#!/bin/sh
set -e

submit=true
push=true
for arg in "$@"; do
    if [ "$arg" = "--no-submit" ]; then
	submit=false
    fi
    if [ "$arg" = "--no-push" ]; then
	push=false
    fi
done

if [ "$1" = "fixup" ] || [ "$1" = "f" ]; then
	git add -A
	git history fixup HEAD
	if [ "$push" = true ]; then
		gh stack push
	fi
	exit 0
fi

message="$1"
current_branch=$(git branch --show-current)
default_branch=$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name')

if [ "$current_branch" = "$default_branch" ]; then
	new_branch="quick-stack/$(date +%Y%m%d%H%M%S)"
	gh stack init "$new_branch"
	git add -A
	git commit -m "$message"
else
	gh stack add -Am "$message"
fi


if [ "$push" = true ]; then
	if [ "$submit" = true ]; then
		gh stack submit # submit also pushes
	else
		gh stack push
	fi
fi

